### ISSUE TITLE
Poor resolution icon very difficult to read

### ISSUE THREAD

**Issue by BPretzel** [medhachaitanya/Pure-Battery-Analytics#13]
Hi,
I had the PureBattery add on installed on my old windows 11 machine (which failed) and have just installed on my replacement new machine. The font on the task bar is very difficult to read - even though I have sent the colours (light theme, black font), size and other aspects. I don't recall this being an issue before (I was using a dark theme though) but it really spoils the effect of the add on... The battery charge is being rendered as a graphic, it seems, not a font... Any way to fix?

**Comment by medhachaitanya** [comment]
Hi BPretzel, I have released an update to the add-on application. I changed the logic and way the icon is rendered. Could you please try installing the latest version and let me know? Here's the link to the latest add-on: 
https://www.microsoft.com/store/productId/9N3HDTNCF6Z8

**Comment by rplaye** [comment]
Hello,

I am experiencing the same problem. The icon was sharp until a few days ago, when the microsoft store updated it to 1.0.22.0 I think and it became fuzzy. The problem is similar to an app having issues with high DPI settings.

Today I received update 1.0.23.0 and the problem persists.

The add-on settings screen is also fuzzy.

I am running windows 10 with resolution 1920x1080 at 125% scale factor.

Thanks for creating this app, hopefully the problem is fixable.

**Comment by medhachaitanya** [comment]
Thanks for sharing. Can you try and verify if it's the same on a fresh install as well ?

You can uninstall and reinstall the app.  
I appreciate your efforts to help and make this better.  

A screenshot would also be very helpful.  

I'm looking forward to your response.

Thanks. 

Regards,
Medha.

**Comment by rplaye** [comment]
I tried uninstalling and reinstalling and unfortunately the issue remains. Here's a screenshot showing the icon as well as the settings page. You can see the the icon is very fuzzy compared to the other systray icons, as well as teh text in the settings page.

![Screenshot 2023-05-26 220323](https://github.com/medhachaitanya/PureBatteryAnalytics/assets/33089269/97f6e4f1-551a-478f-a2b5-d302262ce949)

**Comment by BPretzel** [comment]
Many thanks for the update.

I have installed the update (fresh instal as I had uninstalled the previous version). First impressions are good – seems to be working very well (though the white font colour which is the default for idle battery status does not show properly so I have simply changed that to black).

Best wishes, Boris.

**Comment by kennylee60** [comment]
At high resolution, as in the above question, I hope to solve this problem
![屏幕截图 2023-05-28 091229](https://github.com/medhachaitanya/PureBatteryAnalytics/assets/32236132/0a74239c-4bf5-475e-9ffb-826db1cd1340)
![屏幕截图 2023-05-28 091303](https://github.com/medhachaitanya/PureBatteryAnalytics/assets/32236132/1eeea0ce-1fe4-49be-b2d2-4176068f8823)

**Comment by medhachaitanya** [comment]
Thank you for sharing.  I will investigate this further.

**Comment by medhachaitanya** [comment]
I am releasing an app update today. Please update the app when it's available. Feel free to reopen the issue if it doesn't fix the issue.

**Comment by rplaye** [comment]
I just installed the update. It's definitely better than it used to be, yet the icon numbers don't seem to be as sharp as the other icons in the systray, as shown in the screenshot attached. Also the right click menu and the settings still are fuzzy so there still seems  to be some sort of scaling issue going on. Thanks again for your work with this app.

![Screenshot 2023-06-03 202056](https://github.com/medhachaitanya/PureBatteryAnalytics/assets/33089269/f2f7053e-a49f-44c1-b095-6811a7e15f99)

**Comment by medhachaitanya** [comment]
Thank you for sharing this @rplaye. Did you try the @kennylee60 's recommendation to use a bold icon?

**Comment by rplaye** [comment]
Yes I've tried using a bold icon, indeed it makes the problem less noticeable although the icon still does not seem to be as sharp as the other icons.

Out of curiosity, is it not possible to go back to the old way of rendering the icon, as it used to have no problem with scaling as far as I can remember ?

**Comment by medhachaitanya** [comment]
Sure, we can revert to that, but I'm afraid it could be a breaking change.  Instead, I'll optimize this. I'm gonna work on this.  Would you mind if I ask you to reach out to me at medhachaitanya@outlook.com so that we can test it faster n together with fewer updates to everyone ?

Let me know. Thanks.  Medha

**Comment by BPretzel** [comment]
Happy to be copied in and try occasional updates.

On my system, the icon is OK with non bolded font (better than bolded font) after an initial (very poor) image which persists for a few 10ths of a second when I first click the task tray… It is not perfect and seems to render as a graphic rather than a font (other icons with including text seem to render the text as a font or maybe vector graphic and perform better) but I will live with that anyway (though if you find a solution, that woud be great too).

Best wishes, Boris.

**Comment by kennylee60** [comment]
> I am releasing an app update today. Please update the app when it's available. Feel free to reopen the issue if it doesn't fix the issue.

not fix yet

**Comment by medhachaitanya** [comment]
Released an update.
